'use client';

import { useMemo, useState } from 'react';
import { refresherRecords, traineeProcesses } from '@/lib/mock-data';

export default function TeamLeaderUpdatePage() {
  const [department, setDepartment] = useState('All');
  const filtered = useMemo(() => traineeProcesses.filter((item) => department === 'All' || item.department === department), [department]);
  const readyForPre = filtered.filter((item) => item.stage === 'Ready for Pre-Assessment');
  const readyForAssessment = filtered.filter((item) => item.stage === 'Ready for Assessment');
  const retraining = filtered.filter((item) => item.stage === 'Retraining Required');
  const refreshers = refresherRecords.filter((item) => department === 'All' || item.department === department).slice(0, 6);

  return <div className="space-y-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div><h2 className="text-2xl font-semibold">Team Leader Update</h2><p className="mt-2 text-slate-600">Department-level update built from live training and refresher data.</p></div><select className="rounded-xl border border-slate-200 p-3" value={department} onChange={(e) => setDepartment(e.target.value)}><option>All</option><option>Surfacing</option><option>Coating</option></select><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[['Open Items', filtered.length],['Chase Items', filtered.filter((item) => item.followUpFlag === 'CHASE').length],['Ready for Pre-Assessment', readyForPre.length],['Ready for Assessment', readyForAssessment.length]].map(([label, value]) => <article key={label} className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-900">{value}</p></article>)}</div><div className="grid gap-6 lg:grid-cols-2"><article className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><h3 className="text-lg font-semibold">Items Requiring Support</h3><ul className="mt-3 space-y-2 text-sm text-slate-700">{filtered.slice(0, 6).map((item) => <li key={item.id} className="rounded-xl bg-white p-3">{item.trainee} · {item.process} · {item.stage}</li>)}</ul></article><article className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><h3 className="text-lg font-semibold">Refreshers Due</h3><ul className="mt-3 space-y-2 text-sm text-slate-700">{refreshers.map((item) => <li key={item.id} className="rounded-xl bg-white p-3">{item.trainee} · {item.process} · {item.status}</li>)}</ul></article></div><div className="grid gap-6 lg:grid-cols-3"><article className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><h3 className="text-lg font-semibold">Ready for Pre-Assessment</h3>{readyForPre.map((item) => <p key={item.id} className="mt-2 text-sm text-slate-700">{item.trainee} / {item.process}</p>)}</article><article className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><h3 className="text-lg font-semibold">Ready for Assessment</h3>{readyForAssessment.map((item) => <p key={item.id} className="mt-2 text-sm text-slate-700">{item.trainee} / {item.process}</p>)}</article><article className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><h3 className="text-lg font-semibold">Retraining Required</h3>{retraining.map((item) => <p key={item.id} className="mt-2 text-sm text-slate-700">{item.trainee} / {item.process}</p>)}</article></div></div>;
}
